[package]
name = "dust_bunny"
version = "0.1.0"
edition = "2024"
description = "simple library for rendering particle simulations"
license = "AGPL-3.0"
repository = "https://github.com/skoove/dust_bunny"

[dependencies]
